routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::group(['prefix' => 'backend', 'middleware' => 'auth'], function () {

    Route::view('/', 'backend.index');
    Route::resource('projects', 'ProjectController' , ['except' => 'show']);

    Route::resource('reviews', 'ReviewController' , ['except' => 'show']);

    Route::group(['prefix'=>'leads'], function() {
        Route::get('/', 'LeadController@index')->name('leads.index');
        Route::get('{lead}', 'LeadController@show')->name('leads.show');
        Route::delete('{lead}', 'LeadController@destroy')->name('leads.destroy');
    });

    Route::resource('cities', 'CityController' , ['except' => 'show']);

});

Route::post('/leads', 'LeadController@store')->name('leads.store');


Route::get('/{city}', 'HomeController@index')->name('home');

Route::get('/{city}', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('welcome', [
        'city' => [
            'name' => 'Россия',
            'url' => 'россия',
            'bx_code' => '786'
        ]
    ]);
});

Route::get('/imager/{image}', 'ImagerController@image')->name('imager.image');

// Route::get('/', function () {
//     return redirect()->route('leads.index');
// });

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    public $timestamps = false;
    
    protected $fillable = [
        'name', 'name_formatted', 'url', 'bx_code', 'email', 'phone', 'whatsapp', 'status'
    ];

}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\City;
use Illuminate\Http\Request;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cities = City::All();

        $data = [
            'title' => 'Города',
            'cities' => $cities,
        ];

        return view('backend.city.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'title' => 'Новый город',
        ];

        return view('backend.city.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->except('_token');
         
        $city = City::create($input);

        if ($city->save()) {    
            return redirect()->route('cities.index')->with('status','Город добавлен');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function edit(City $city)
    {

        $old = $city->toArray();

        $data = [
            'name' => 'Редактирование города - '.$old['name'],
            'data' => $old,
            'city' => $city
        ];

        return view('backend.city.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, City $city)
    {
        $input = $request->except('_token');

        $city->fill($input);

        if($city->update()) {  
            return redirect()->route('cities.index')->with('status', 'Информация обновлена');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function destroy(City $city)
    {
        $city->delete();

        return redirect()->route('cities.index')->with('status','Город удален');
    }
}

resources/views/backend/city/create.blade.php
@extends('backend.index') 
@section('section')

{!! Form::open(['url' => route('cities.store'), 'class'=>'row', 'method'=>'POST','enctype'=>'multipart/form-data']) !!}

<div class="col-sm-12 form-row mT-10 mB-10">
    <h4 class="col-sm-6 c-grey-900">{{$title}}</h4>
    <div class="text-right col-sm-6">
       
        {!! Html::link(route('cities.index'),'Вернуться к списку',['class'=>'btn cur-p btn-secondary']) !!}
        {{ Form::submit('Сохранить', array('class' => 'btn btn-primary')) }}
        
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="form-group col-md-3">
                    {{ Form::label('name', 'Название') }} 
                    {{ Form::text('name', null, array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('name_formatted', 'Форматированное название') }} 
                    {{ Form::text('name_formatted', null, array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('url', 'URL') }} 
                    {{ Form::text('url', null, array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('bx_code', 'Код города в Битрикс') }} 
                    {{ Form::text('bx_code', null, array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('email', 'E-mail') }} 
                    {{ Form::text('email', null, array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('phone', 'Телефон') }} 
                    {{ Form::text('phone', null, array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('whatsapp', 'WhatsApp') }} 
                    {{ Form::text('whatsapp', null, array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('status', 'Статус') }}
                    {!! Form::select('status', array('active' => 'Активно', 'deactived' => 'Скрыто'), null,  array('class' => 'form-control')) !!} 
                </div>
            </div>
        </div>
    </div>
</div>

{!! Form::close() !!}


@endsection

resources/views/backend/city/edit.blade.php
@extends('backend.index') 
@section('section')

{!! Form::open(['url' => route('cities.update',array('city'=>$data['id'])), 'class'=>'row', 'method'=>'POST','enctype'=>'multipart/form-data']) !!} 
{!! Form::hidden('_method', 'patch') !!} 
{!! Form::hidden('id', $data['id']) !!}

<div class="col-sm-12 form-row mT-10 mB-10">
    <h4 class="col-sm-6 c-grey-900">{{$name}}</h4>
    <div class="text-right col-sm-6">
       
        {!! Html::link(route('cities.index'),'Вернуться к списку',['class'=>'btn cur-p btn-secondary']) !!}
        {{ Form::submit('Сохранить', array('class' => 'btn btn-primary')) }}
        
        
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="form-group col-md-3">
                    {{ Form::label('name', 'Название') }} 
                    {{ Form::text('name', $data['name'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('name_formatted', 'Форматированное название') }} 
                    {{ Form::text('name_formatted', $data['name_formatted'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('url', 'URL') }} 
                    {{ Form::text('url', $data['url'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('bx_code', 'Код города в Битрикс') }} 
                    {{ Form::text('bx_code', $data['bx_code'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('email', 'E-mail') }} 
                    {{ Form::text('email', $data['email'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('phone', 'Телефон') }} 
                    {{ Form::text('phone', $data['phone'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('whatsapp', 'WhatsApp') }} 
                    {{ Form::text('whatsapp', $data['whatsapp'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-3">
                    {{ Form::label('status', 'Статус') }}
                    {!! Form::select('status', array('active' => 'Активно', 'deactived' => 'Скрыто'), $data['status'],  array('class' => 'form-control')) !!} 
                </div>
            </div>
        </div>
    </div>
</div>


{!! Form::close() !!}

@endsection

resources/views/backend/city/index.blade.php
@extends('backend.index')

@section('section')

<div class="container-fluid">
    <h4 class="c-grey-900 mT-10 mB-30">{{$title}}</h4>

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">

                <div class="text-right form-group">
                    <a href="{{ route('cities.create') }}" class="btn cur-p btn-primary">Создать</a>
                </div>

                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Название</th>
                            <th scope="col">URL</th>
                            <th scope="col">Код Битрикса</th>
                            <th scope="col">Телефон</th>
                            <th scope="col">E-mail</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    
                    <tbody>
                       @foreach($cities as $city)
                       <tr {!! $city->status === 'deactived' ? 'style="background-color: rgba(0,0,0,.05);}"' : '' !!}>
                                <th scope="row">{{ $city->name }}</th>
                                <td>{{ $city->url }}</td>
                                <td>{{ $city->bx_code}}</td>
                                <td>{{ $city->phone}}</td>
                                <td>{{ $city->email}}</td>
                                <td>

                                    {!! Form::open(['url' => route('cities.destroy',['city'=>$city->id]),'class'=>'text-right  gap-10','method'=>'POST']) !!}

                                    {{ method_field('DELETE') }}

                                    {!! Form::button('Удалить', ['class' => 'btn cur-p btn-outline-danger','type'=>'submit']) !!}

                                    {!! Html::link(route('cities.edit',['city'=>$city->id]),'Редактировать',['class'=>'btn cur-p btn-outline-primary']) !!}

                                    {!! Form::close() !!}

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

@endsection