routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::group(['prefix' => 'backend', 'middleware' => 'auth'], function () {

    Route::view('/', 'backend.index');
    Route::resource('projects', 'ProjectController' , ['except' => 'show']);

    Route::resource('reviews', 'ReviewController' , ['except' => 'show']);

    Route::group(['prefix'=>'leads'], function() {
        Route::get('/', 'LeadController@index')->name('leads.index');
        Route::get('{lead}', 'LeadController@show')->name('leads.show');
        Route::delete('{lead}', 'LeadController@destroy')->name('leads.destroy');
    });

    Route::resource('cities', 'CityController' , ['except' => 'show']);

});

Route::post('/leads', 'LeadController@store')->name('leads.store');


Route::get('/{city}', 'HomeController@index')->name('home');

Route::get('/{city}', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('welcome', [
        'city' => [
            'name' => 'Россия',
            'url' => 'россия',
            'bx_code' => '786'
        ]
    ]);
});

Route::get('/imager/{image}', 'ImagerController@image')->name('imager.image');

// Route::get('/', function () {
//     return redirect()->route('leads.index');
// });

resources/views/backend/footer.blade.php
<footer class="bdT ta-c p-30 lh-0 fsz-sm c-grey-600"><span>Copyright © 2017 Designed by <a href="https://colorlib.com" target="_blank" title="Colorlib">Colorlib</a>. All rights reserved.</span></footer>

resources/views/backend/header.blade.php
<div class="header navbar">
    <div class="header-container">
        <ul class="nav-left">
            <li><a id="sidebar-toggle" class="sidebar-toggle" href="javascript:void(0);"><i class="ti-menu"></i></a></li>
        </ul>
        <ul class="nav-right">
            <li>
                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>
            </li>
        </ul>
    </div>
</div>

resources/views/backend/index.blade.php
@extends('layouts.admin')


@section('sidebar')

    @include('backend.sidebar')  

@endsection

@section('content')

    <div class="page-container">  
      
        @include('backend.header')

        <main class="main-content bgc-grey-100">
            <div id="mainContent">
              
               @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                
                @yield('section')
            </div>
        </main>

        @include('backend.footer')
    
    </div>

@endsection

resources/views/backend/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-inner">
        <div class="sidebar-logo">
            <div class="peers ai-c fxw-nw">
                <div class="peer peer-greed">
                    <a class="sidebar-link td-n" href="/">
                        <div class="peers ai-c fxw-nw">
                            <div class="peer">
                                <div class="logo"><img src="{{ asset('img/gui/logo_square.svg') }}" alt="trend-pro"></div>
                            </div>
                            <div class="peer peer-greed">
                                <h5 class="lh-1 mB-0 logo-text">Перейти на сайт</h5>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="peer">
                    <div class="mobile-toggle sidebar-toggle"><a href="" class="td-n"><i class="ti-arrow-circle-left"></i></a></div>
                </div>
            </div>
        </div>
        <ul class="sidebar-menu scrollable pos-r">
            <li class="nav-item mT-30">
                <a href="{{ route('projects.index') }}" class="sidebar-link">
                    <span class="icon-holder">
                        <i class="c-blue-500 ti-files"></i> 
                    </span>
                    <span class="title">Работы</span>
                </a>
            </li>
            <li class="nav-item mT-30">
                <a href="{{ route('leads.index') }}" class="sidebar-link">
                    <span class="icon-holder">
                        <i class="c-blue-500 ti-files"></i> 
                    </span>
                    <span class="title">Заявки</span>
                </a>
            </li>
            <li class="nav-item mT-30">
                <a href="{{ route('reviews.index') }}" class="sidebar-link">
                    <span class="icon-holder">
                        <i class="c-blue-500 ti-files"></i> 
                    </span>
                    <span class="title">Отзывы</span>
                </a>
            </li>
            <li class="nav-item mT-30">
                <a href="{{ route('cities.index') }}" class="sidebar-link">
                    <span class="icon-holder">
                        <i class="c-blue-500 ti-files"></i> 
                    </span>
                    <span class="title">Города</span>
                </a>
            </li>
        </ul>
    </div>
</div>