routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::group(['prefix' => 'backend', 'middleware' => 'auth'], function () {

    Route::view('/', 'backend.index');
    Route::resource('projects', 'ProjectController' , ['except' => 'show']);

    Route::resource('reviews', 'ReviewController' , ['except' => 'show']);

    Route::group(['prefix'=>'leads'], function() {
        Route::get('/', 'LeadController@index')->name('leads.index');
        Route::get('{lead}', 'LeadController@show')->name('leads.show');
        Route::delete('{lead}', 'LeadController@destroy')->name('leads.destroy');
    });

    Route::resource('cities', 'CityController' , ['except' => 'show']);

});

Route::post('/leads', 'LeadController@store')->name('leads.store');


Route::get('/{city}', 'HomeController@index')->name('home');

Route::get('/{city}', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('welcome', [
        'city' => [
            'name' => 'Россия',
            'url' => 'россия',
            'bx_code' => '786'
        ]
    ]);
});

Route::get('/imager/{image}', 'ImagerController@image')->name('imager.image');

// Route::get('/', function () {
//     return redirect()->route('leads.index');
// });

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    public $timestamps = false;
    
    protected $fillable = [
        'name', 'img', 'type', 'price', 'area', 'status'
    ];
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use File;
use Illuminate\Support\Str;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::All();

        $data = [
            'title' => 'Примеры работ',
            'projects' => $projects,
        ];

        return view('backend.project.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'title' => 'Новый пример работ',
        ];

        return view('backend.project.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->except('_token');
         
        if($request->file()):
            $dir = public_path('uploads/projects/');
            $file = $request->file('img');
            $name = Str::random(5) .'.' . $file->getClientOriginalExtension() ?: 'jpg';
            $img = Image::make($file);
            $img->save($dir . $name);
            $input['img'] = $name;
        endif;

        $project = Project::create($input);

        if ($project->save()) {    
            return redirect()->route('projects.index')->with('status','Пример добавлен');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        $old = $project->toArray();

        if($project->img){

            $dir = public_path('uploads/projects/');
     
            if(file_exists($dir . $project->img)):

                    $general[] = [
                        "name" => $project->img,
                        "size" => filesize($dir . $project->img),
                        "file" => $project->img,
                        "data" => array(
                            "thumbnail" => '/uploads/projects/' . $project->img,
                        ),
                    ];
            endif;

            $preLoadImg = [];
            $general = isset($general) ? json_encode($general) : null;
            array_push($preLoadImg, $general);
  
        }else{
            $preLoadImg = null;
        }

        $data = [
            'name' => 'Редактирование работы - '.$old['name'],
            'data' => $old,
            'project' => $project,
            'preLoadImg' => $preLoadImg,
        ];

        return view('backend.project.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        $input = $request->except('_token');

        $dir = public_path('uploads/projects/');

        if(!json_decode($request->general_photo, true)){

            File::delete($dir . $project->img);

            $input['img'] = null;
        }
        if($request->file()):
            
            $file = $request->file('img');
            $name = Str::random(5) .'.' . $file->getClientOriginalExtension() ?: 'jpg';
            $img = Image::make($file);
            $img->save($dir . $name);
            $input['img'] = $name;
        endif;

        $project->fill($input);

        if($project->update()) {  
            return redirect()->route('projects.index')->with('status', 'Информация обновлена');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        $dir = public_path('uploads/projects/');
        File::delete($dir . $project->img);
        $project->delete();

        return redirect()->route('projects.index')->with('status','Проект удален');
    }
}

resources/views/backend/project/create.blade.php
@extends('backend.index') 
@section('section')

{!! Form::open(['url' => route('projects.store'), 'class'=>'row', 'method'=>'POST','enctype'=>'multipart/form-data']) !!}

<div class="col-sm-12 form-row mT-10 mB-10">
    <h4 class="col-sm-6 c-grey-900">{{$title}}</h4>
    <div class="text-right col-sm-6">
       
        {!! Html::link(route('projects.index'),'Вернуться к списку',['class'=>'btn cur-p btn-secondary']) !!}
        {{ Form::submit('Сохранить', array('class' => 'btn btn-primary')) }}
        
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ Form::label('name', 'Название') }} 
                    {{ Form::text('name', null, array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('status', 'Статус') }}
                    {!! Form::select('status', array('active' => 'Активно', 'deactived' => 'Скрыто'), null,  array('class' => 'form-control')) !!} 
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('type', 'Тип потолка') }} 
                    {{ Form::text('type', null, array('class'=>'form-control')) }} 
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('price', 'Цена') }} 
                    {{ Form::text('price', null, array('class'=>'form-control')) }} 
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('area', 'Площадь, м2') }} 
                    {{ Form::text('area', null, array('class'=>'form-control')) }} 
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="col-md-12">
                    <div class="bgc-white p-20 bd">
                        <div class="mT-30">
                            <div class="form-group">
                                {{ Form::label('img', 'Изображение') }}
                                {!! Form::file('img', array('class' => 'general-img')) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{!! Form::close() !!}


@endsection

resources/views/backend/project/edit.blade.php
@extends('backend.index') 
@section('section')

{!! Form::open(['url' => route('projects.update',array('project'=>$data['id'])), 'class'=>'row', 'method'=>'POST','enctype'=>'multipart/form-data']) !!} 
{!! Form::hidden('_method', 'patch') !!} 
{!! Form::hidden('id', $data['id']) !!}

<div class="col-sm-12 form-row mT-10 mB-10">
    <h4 class="col-sm-6 c-grey-900">{{$name}}</h4>
    <div class="text-right col-sm-6">
       
        {!! Html::link(route('projects.index'),'Вернуться к списку',['class'=>'btn cur-p btn-secondary']) !!}
        {{ Form::submit('Сохранить', array('class' => 'btn btn-primary')) }}
        
        
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ Form::label('name', 'Название') }} 
                    {{ Form::text('name', $data['name'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('status', 'Статус') }}
                    {!! Form::select('status', array('active' => 'Активно', 'deactived' => 'Скрыто'), $data['status'],  array('class' => 'form-control')) !!} 
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('type', 'Тип потолка') }} 
                    {{ Form::text('type', $data['type'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('price', 'Цена') }} 
                    {{ Form::text('price', $data['price'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('area', 'Площадь, м2') }} 
                    {{ Form::text('area', $data['area'], array('class'=>'form-control')) }}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="col-md-12">
                    <div class="bgc-white p-20 bd">
                        <div class="mT-30">
                            <div class="form-group">
                                {{ Form::label('img', 'Изображение') }}
                                {!! Form::file('img', array('class' => 'general-img', 'data-fileuploader-listInput' => 'general_photo', 'data-fileuploader-files' => $preLoadImg[0])) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{!! Form::close() !!}

@endsection

resources/views/backend/project/index.blade.php
@extends('backend.index')

@section('section')

<div class="container-fluid">
    <h4 class="c-grey-900 mT-10 mB-30">{{$title}}</h4>

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">

                <div class="text-right form-group">
                    <a href="{{ route('projects.create') }}" class="btn cur-p btn-primary">Создать</a>
                </div>

                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Название</th>
                            <th scope="col">Тип потолка</th>
                            <th scope="col">Цена</th>
                            <th scope="col">Площадь, м2</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    
                    <tbody>
                       @foreach($projects as $project)
                       <tr {!! $project->status === 'deactived' ? 'style="background-color: rgba(0,0,0,.05);}"' : '' !!}>
                                <th scope="row">{{ $project->id }}</th>
                                <td>{{ $project->name }}</td>
                                <td>{{ $project->type}}</td>
                                <td>{{ $project->price}}</td>
                                <td>{{ $project->area}}</td>
                                <td>

                                    {!! Form::open(['url' => route('projects.destroy',['project'=>$project->id]),'class'=>'text-right  gap-10','method'=>'POST']) !!}

                                    {{ method_field('DELETE') }}

                                    {!! Form::button('Удалить', ['class' => 'btn cur-p btn-outline-danger','type'=>'submit']) !!}

                                    {!! Html::link(route('projects.edit',['project'=>$project->id]),'Редактировать',['class'=>'btn cur-p btn-outline-primary']) !!}

                                    {!! Form::close() !!}

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

@endsection