routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::group(['prefix' => 'backend', 'middleware' => 'auth'], function () {

    Route::view('/', 'backend.index');
    Route::resource('projects', 'ProjectController' , ['except' => 'show']);

    Route::resource('reviews', 'ReviewController' , ['except' => 'show']);

    Route::group(['prefix'=>'leads'], function() {
        Route::get('/', 'LeadController@index')->name('leads.index');
        Route::get('{lead}', 'LeadController@show')->name('leads.show');
        Route::delete('{lead}', 'LeadController@destroy')->name('leads.destroy');
    });

    Route::resource('cities', 'CityController' , ['except' => 'show']);

});

Route::post('/leads', 'LeadController@store')->name('leads.store');


Route::get('/{city}', 'HomeController@index')->name('home');

Route::get('/{city}', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('welcome', [
        'city' => [
            'name' => 'Россия',
            'url' => 'россия',
            'bx_code' => '786'
        ]
    ]);
});

Route::get('/imager/{image}', 'ImagerController@image')->name('imager.image');

// Route::get('/', function () {
//     return redirect()->route('leads.index');
// });

app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use App\Review;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use File;
use Illuminate\Support\Str;

class ReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reviews = Review::All();

        $data = [
            'title' => 'Отзывы',
            'reviews' => $reviews,
        ];

        return view('backend.review.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'title' => 'Новый отзыв',
        ];

        return view('backend.review.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->except('_token');
         
        if($request->file()):
            $dir = public_path('uploads/reviews/');
            $files = $request->file();
            foreach($files as $tag => $array){
                foreach($array as $file){
                    $name = Str::random(5) .'.' . $file->getClientOriginalExtension() ?: 'jpg';
                    $img = Image::make($file);
                    $img->save($dir . $name);
                    $input[$tag] = $name;
                }
            }
        endif;

        $review = Review::create($input);

        if ($review->save()) {    
            return redirect()->route('reviews.index')->with('status','Отзыв добавлен');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Review  $review
     * @return \Illuminate\Http\Response
     */
    public function edit(Review $review)
    {
        $old = $review->toArray();

        $dir = public_path('uploads/reviews/');

        if($review->avatar){

            if(file_exists($dir . $review->avatar)):

                $avatar = [
                    "name" => $review->avatar,
                    "size" => filesize($dir . $review->avatar),
                    "file" => $review->avatar,
                    "data" => array(
                        "thumbnail" => '/uploads/reviews/' . $review->avatar,
                    ),
                ];
            endif;

            $avatar = isset($avatar) ? json_encode($avatar) : null;

        }else{
            $avatar = NULL;
        }

        if($review->images){

            if(file_exists($dir . $review->images)):

                $images = [
                    "name" => $review->images,
                    "size" => filesize($dir . $review->images),
                    "file" => $review->images,
                    "data" => array(
                        "thumbnail" => '/uploads/reviews/' . $review->images,
                    ),
                ];
            endif;

            $images = isset($images) ? json_encode($images) : null;

        }else{
            $images = NULL;
        }

        $data = [
            'name' => 'Редактирование отзыва - '.$old['name'],
            'data' => $old,
            'project' => $review,
            'avatar' => $avatar,
            'images' => $images
        ];

        return view('backend.review.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Review  $review
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Review $review)
    {
        $input = $request->except('_token');

        // dd($input['source']);

        $dir = public_path('uploads/reviews/');

        if(!json_decode($request->avatar, true)){

            File::delete($dir . $review->avatar);

            $input['avatar'] = null;
            
        }

        if($request->file('avatar')):
            $dir = public_path('uploads/reviews/');
            
            if($review->avatar):   
                File::delete($dir . $review->avatar);
            endif;
        
            $file = $request->file('avatar');
            $name = Str::random(5) .'.' . $file->getClientOriginalExtension() ?: 'jpg';
            $img = Image::make($file);
            $img->save($dir . $name);
            $input['avatar'] = $name;
        else:

            if(!json_decode($request->avatar, true)):
                File::delete($dir . $review->avatar);
    
                $input['avatar'] = null;
            else:
                $input['avatar'] = $review->avatar;
            endif;
            
        endif;

        if($request->file('images')):
            $dir = public_path('uploads/reviews/');
            
            if($review->images):   
                File::delete($dir . $review->avatar);
            endif;
        
            $file = $request->file('images');
            $name = Str::random(5) .'.' . $file->getClientOriginalExtension() ?: 'jpg';
            $img = Image::make($file);
            $img->save($dir . $name);
            $input['images'] = $name;
        else:

            if(!json_decode($request->images, true)):
                File::delete($dir . $review->images);
    
                $input['images'] = null;
            else:
                $input['images'] = $review->images;
            endif;

        endif;


        $review->fill($input);

        if($review->update()) {  
            return redirect()->route('reviews.index')->with('status', 'Информация обновлена');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Review  $review
     * @return \Illuminate\Http\Response
     */
    public function destroy(Review $review)
    {
        $dir = public_path('uploads/reviews/');
        File::delete($dir . $review->avatar);
        File::delete($dir . $review->images);
        $review->delete();

        return redirect()->route('reviews.index')->with('status','Отзыв удален');
    }
}

resources/views/backend/review/create.blade.php
@extends('backend.index') 
@section('section')

{!! Form::open(['url' => route('reviews.store'), 'class'=>'row', 'method'=>'POST','enctype'=>'multipart/form-data']) !!}

<div class="col-sm-12 form-row mT-10 mB-10">
    <h4 class="col-sm-6 c-grey-900">{{$title}}</h4>
    <div class="text-right col-sm-6">
       
        {!! Html::link(route('reviews.index'),'Вернуться к списку',['class'=>'btn cur-p btn-secondary']) !!}
        {{ Form::submit('Сохранить', array('class' => 'btn btn-primary')) }}
        
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ Form::label('name', 'Имя') }} 
                    {{ Form::text('name', null, array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('status', 'Статус') }}
                    {!! Form::select('status', array('active' => 'Активно', 'deactived' => 'Скрыто'), null,  array('class' => 'form-control')) !!} 
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('source', 'Источник отзыва') }}
                    {!! Form::select('source', array('' => 'Не выбрано', 'inst' => 'instagram', 'facebook' => 'facebook', 'vk' => 'ВКонтакте', 'ok' => 'Одноклассники'), null,  array('class' => 'form-control')) !!} 
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('date', 'Дата') }} 
                    {{ Form::text('date', null, array('class'=>'form-control')) }} 
                </div>
            </div>
            <div class="form-row mT-30">
                <div class="form-group col-md-12">
                    {{ Form::label('text', 'Текст отзыва') }}
                    {{ Form::textarea('text', null, array('class' => 'form-control')) }}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="col-md-12">
                    <div class="mT-30">
                        <div class="form-group">
                            {{ Form::label('avatar', 'Аватар') }}
                            {!! Form::file('avatar[]', array('class' => 'general-img')) !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="mT-30">
                        <div class="form-group">
                            {{ Form::label('images', 'Изображение к отзыву') }}
                            {!! Form::file('images[]', array('class' => 'general-img')) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{!! Form::close() !!}


@endsection

resources/views/backend/review/edit.blade.php
@extends('backend.index') 
@section('section')

{!! Form::open(['url' => route('reviews.update',array('review'=>$data['id'])), 'class'=>'row', 'method'=>'POST','enctype'=>'multipart/form-data']) !!} 
{!! Form::hidden('_method', 'patch') !!} 
{!! Form::hidden('id', $data['id']) !!}

<div class="col-sm-12 form-row mT-10 mB-10">
    <h4 class="col-sm-6 c-grey-900">{{$name}}</h4>
    <div class="text-right col-sm-6">
       
        {!! Html::link(route('reviews.index'),'Вернуться к списку',['class'=>'btn cur-p btn-secondary']) !!}
        {{ Form::submit('Сохранить', array('class' => 'btn btn-primary')) }}
        
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ Form::label('name', 'Имя') }} 
                    {{ Form::text('name', $data['name'], array('class'=>'form-control')) }}
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('status', 'Статус') }}
                    {!! Form::select('status', array('active' => 'Активно', 'deactived' => 'Скрыто'), $data['status'],  array('class' => 'form-control')) !!} 
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('source', 'Источник отзыва') }}
                    {!! Form::select('source', array('' => 'Не выбрано', 'inst' => 'instagram', 'facebook' => 'facebook', 'vk' => 'ВКонтакте', 'ok' => 'Одноклассники'), $data['source'],  array('class' => 'form-control')) !!} 
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('date', 'Дата') }} 
                    {{ Form::text('date', $data['date'], array('class'=>'form-control')) }} 
                </div>
            </div>
            <div class="form-row mT-30">
                <div class="form-group col-md-12">
                    {{ Form::label('text', 'Текст отзыва') }}
                    {{ Form::textarea('text', $data['text'], array('class' => 'form-control')) }}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-12 mT-20">
    <div class="bgc-white p-20 bd">
        <div class="mT-30">
            <div class="form-row">
                <div class="col-md-12">
                    <div class="mT-30">
                        <div class="form-group">
                            {{ Form::label('avatar', 'Аватар') }}
                            {!! Form::file('avatar', array('class' => 'general-img', 'data-fileuploader-listInput' => 'avatar', 'data-fileuploader-files' => $avatar)) !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="mT-30">
                        <div class="form-group">
                            {{ Form::label('images', 'Изображение к отзыву') }}
                            {!! Form::file('images', array('class' => 'general-img', 'data-fileuploader-listInput' => 'images', 'data-fileuploader-files' => $images)) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{!! Form::close() !!}

@endsection

resources/views/backend/review/index.blade.php
@extends('backend.index')

@section('section')

<div class="container-fluid">
    <h4 class="c-grey-900 mT-10 mB-30">{{$title}}</h4>

    <div class="row">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20 mB-20">

                <div class="text-right form-group">
                    <a href="{{ route('reviews.create') }}" class="btn cur-p btn-primary">Создать</a>
                </div>

                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Имя</th>
                            <th scope="col">Аватар</th>
                            <th scope="col">Текст</th>
                            <th scope="col">Изображение</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    
                    <tbody>
                       @foreach($reviews as $review)
                            <tr {!! $review->status === 'deactived' ? 'style="background-color: rgba(0,0,0,.05);}"' : '' !!}>
                                <th scope="row">{{ $review->id }}</th>
                                <td>{{ $review->name }}</td>
                                <td>{{ $review->avatar}}</td>
                                <td>{{ $review->text}}</td>
                                <td>{{ $review->images}}</td>
                                <td>

                                    {!! Form::open(['url' => route('reviews.destroy',['review'=>$review->id]),'class'=>'text-right  gap-10','method'=>'POST']) !!}

                                    {{ method_field('DELETE') }}

                                    {!! Form::button('Удалить', ['class' => 'btn cur-p btn-outline-danger','type'=>'submit']) !!}

                                    {!! Html::link(route('reviews.edit',['review'=>$review->id]),'Редактировать',['class'=>'btn cur-p btn-outline-primary']) !!}

                                    {!! Form::close() !!}

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

@endsection